services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=danger
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs
    container_name: DB
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://danger:123@db:5432/nestjs?schema=public
    ports:
      - "3000:3000"
    container_name: SERVER
    networks:
      - app-network
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    container_name: CLIENT
    networks:
      - app-network
    depends_on:
      - server
networks:
  app-network:
    driver: bridge